### ISSUE TITLE
Exception in thread "main" java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by nsgarcia27** [broadinstitute/pilon#102]
Hello, 

I keep getting the error below whenever I run Pilon

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at org.broadinstitute.pilon.GenomeRegion.<init>(GenomeRegion.scala:55)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$contigRegions$1.apply(GenomeFile.scala:72)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$contigRegions$1.apply(GenomeFile.scala:72)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.Range.foreach(Range.scala:160)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.broadinstitute.pilon.GenomeFile.contigRegions(GenomeFile.scala:72)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$2.apply(GenomeFile.scala:52)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$2.apply(GenomeFile.scala:52)
        at scala.collection.immutable.List.map(List.scala:277)
        at org.broadinstitute.pilon.GenomeFile.<init>(GenomeFile.scala:52)
        at org.broadinstitute.pilon.Pilon$.main(Pilon.scala:98)
        at org.broadinstitute.pilon.Pilon.main(Pilon.scala)
        ... 6 more

I read in one of the threads here it is due to insufficient memory. However, I already increased the memory to 512GB and I am still getting this error. My genome is 1.5 Gb

Are there any other factors that might be giving this error aside from insufficient memory?

Nelson

**Comment by onkarnath89** [comment]
I had the similar error
by adding -Xmx200G as a parameter the error was resolved. I am using pilon from github not the jar file
