### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by SvitlanaLukicheva** [broadinstitute/pilon#105]
Hello,

I try to run Pilon with the following command:
```
java -Xmx512G -jar pilon-1.23.jar --genome genome.fa --frags illumina_alignment.bam --nanopore nanopore_alignment.bam --changes --vcf --tracks --diploid --threads 16 --verbose
```

and after 12 hours of execution the program stops with the following exception:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 399183
        at org.broadinstitute.pilon.PileUpRegion.homoRun$1(PileUpRegion.scala:121)
        at org.broadinstitute.pilon.PileUpRegion.$anonfun$addRead$5(PileUpRegion.scala:160)
        at org.broadinstitute.pilon.PileUpRegion.$anonfun$addRead$5$adapted(PileUpRegion.scala:145)
        at scala.collection.Iterator.foreach(Iterator.scala:937)
        at scala.collection.Iterator.foreach$(Iterator.scala:937)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
        at scala.collection.IterableLike.foreach(IterableLike.scala:70)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at org.broadinstitute.pilon.PileUpRegion.addRead(PileUpRegion.scala:145)
        at org.broadinstitute.pilon.BamFile.$anonfun$process$1(BamFile.scala:132)
        at org.broadinstitute.pilon.BamFile.$anonfun$process$1$adapted(BamFile.scala:125)
        at scala.collection.Iterator.foreach(Iterator.scala:937)
        at scala.collection.Iterator.foreach$(Iterator.scala:937)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
        at org.broadinstitute.pilon.BamFile.process(BamFile.scala:125)
        at org.broadinstitute.pilon.GenomeRegion.processBam(GenomeRegion.scala:292)
        at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$5(GenomeFile.scala:112)
        at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$5$adapted(GenomeFile.scala:112)
        at scala.collection.immutable.List.foreach(List.scala:388)
        at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$4(GenomeFile.scala:112)
        at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$4$adapted(GenomeFile.scala:109)
        at scala.collection.Iterator.foreach(Iterator.scala:937)
        at scala.collection.Iterator.foreach$(Iterator.scala:937)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:436)
        at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
        Suppressed: java.lang.ArrayIndexOutOfBoundsException: 531604
```

Any idea how to fix it? Thank you in advance :)

**Comment by onkarnath89** [comment]
I had the similar error
by adding -Xmx200G as a parameter the error was resolved. I am using pilon from github not the jar file
