### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException:

### ISSUE THREAD

**Issue by jhcaddisfly** [broadinstitute/pilon#106]
Hello,

I am having problems running Pilon.
I run the following command:
java -Xmx900G -jar pilon-1.23.jar --genome HK1_racon1_nanopolished_genome.fa --frags HK1.paired.sort.bam --unpaired HK1.unpaired.sort.bam --output pilon_HK1_round1_fix_all --outdir pilon1_fixall --changes --vcf --tracks

and I get the following error message:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 40685
	at htsjdk.samtools.AbstractBAMFileIndex.query(AbstractBAMFileIndex.java:314)
	at htsjdk.samtools.DiskBasedBAMFileIndex.getSpanOverlapping(DiskBasedBAMFileIndex.java:61)
	at htsjdk.samtools.BAMFileReader.getFileSpan(BAMFileReader.java:898)
	at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:915)
	at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:575)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:528)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:533)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:395)
	at org.broadinstitute.pilon.BamFile.process(BamFile.scala:118)
	at org.broadinstitute.pilon.GenomeRegion.processBam(GenomeRegion.scala:292)
	at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$5(GenomeFile.scala:112)
	at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$5$adapted(GenomeFile.scala:112)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$4(GenomeFile.scala:112)
	at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$4$adapted(GenomeFile.scala:109)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:166)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:436)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:436)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Suppressed: java.lang.ArrayIndexOutOfBoundsException

Can yo help me fix the issue?
Thanks,

J.

**Comment by aaronphillips7493** [comment]
I am also having this issues. Is there a solution yet?

**Comment by syrenawhitner** [comment]
I am also having this exact same issue and have found no conclusions yet. Please let me know if anybody is able to solve this!

**Comment by onkarnath89** [comment]
I had the similar error.
by adding -Xmx200G as a parameter the error was resolved. I am using the pilon command from github not the jar file
