### ISSUE TITLE
pilon crashed due to memory issues

### ISSUE THREAD

**Issue by mahulchak** [broadinstitute/pilon#11]
Hello,
I am using pilon on a 150Mb genome. I have 120X 150bp illumina PE reads. I am running it on a node with 64 cores and 512Gb memory. But after running for some time, pilon crashed with the following error-

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.OutOfMemoryError: Java heap space

There is more in the error message. Do you know what is causing this?
Thanks.
Mahul

**Comment by mahulchak** [comment]
I did not explicitly set memory for -Xmx. I will try that. how much would
you recommend?
By the way, the insert size for the illumina reads is 5kb. Do you think
this unusually large insert size could be a problem?
