### ISSUE TITLE
Exception in thread "main" 

### ISSUE THREAD

**Issue by Tdanis** [broadinstitute/pilon#110]
Hi , I am not familiar with Java, could you help me please with this kind of error?
my command:
java -jar -Xmx100G pilon-1.23.jar --genome genome.fasta --frags /illumina-data/Minimap_for_Pilon/Pilon/alg.sorted.bam --outdir /home1/tdanis/illumina-data/Minimap_for_Pilon/Pilon --output pilon1 --fix all --changes --verbose --threads 32
 
and after 1 hour running...

Exception in thread "main" java.io.FileNotFoundException: /home1/illumina-data/Minimap_for_Pilon/Pilon/home1/illumina-data/Minimap_for_Pilon/Pilon/pilon1.changes (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.FileWriter.<init>(FileWriter.java:90)
	at org.broadinstitute.pilon.GenomeFile.processRegions(GenomeFile.scala:131)
	at org.broadinstitute.pilon.Pilon$.main(Pilon.scala:105)
	at org.broadinstitute.pilon.Pilon.main(Pilon.scala)

**Comment by marce-sarrias** [comment]
Hi Tdanis,

I'm having a similar issue. How did you fix it? Thanks!

**Comment by Tdanis** [comment]
Hello Marce-sarrias,

You could just re-run the job. After two effrots, it was OK.
Thanks
