### ISSUE TITLE
Exception in thread "main" java.nio.BufferUnderflowException

### ISSUE THREAD

**Issue by francescodc87** [broadinstitute/pilon#124]
Hi all,
I am getting this error and I hope somebody can help.
After using this command:
pilon --genome fastafile.fasta --bam bamfile.bam --output oneP_ --outdir onePfolder

I am getting this error after using this command:

unpaired bamfile.bam: Exception in thread "main" java.nio.BufferUnderflowException
        at java.base/java.nio.ByteBuffer.get(ByteBuffer.java:735)
        at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:319)
        at java.base/java.nio.ByteBuffer.get(ByteBuffer.java:762)
        at htsjdk.samtools.AbstractBAMFileIndex$MemoryMappedFileBuffer.readBytes(AbstractBAMFileIndex.java:493)
        at htsjdk.samtools.AbstractBAMFileIndex.readBytes(AbstractBAMFileIndex.java:438)
        at htsjdk.samtools.AbstractBAMFileIndex.verifyBAMMagicNumber(AbstractBAMFileIndex.java:404)
        at htsjdk.samtools.AbstractBAMFileIndex.<init>(AbstractBAMFileIndex.java:82)
        at htsjdk.samtools.DiskBasedBAMFileIndex.<init>(DiskBasedBAMFileIndex.java:46)
        at htsjdk.samtools.BAMFileReader.getIndex(BAMFileReader.java:403)
        at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:915)
        at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:575)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:528)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:533)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:395)
        at org.broadinstitute.pilon.BamFile.process(BamFile.scala:118)
        at org.broadinstitute.pilon.GenomeRegion.processBam(GenomeRegion.scala:292)
        at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$5(GenomeFile.scala:112)
        at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$5$adapted(GenomeFile.scala:112)
        at scala.collection.immutable.List.foreach(List.scala:388)
        at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$4(GenomeFile.scala:112)
        at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$4$adapted(GenomeFile.scala:109)
        at scala.collection.Iterator.foreach(Iterator.scala:937)
        at scala.collection.Iterator.foreach$(Iterator.scala:937)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:436)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by francescodc87** [comment]
Nobody else having this problem?

**Comment by onkarnath89** [comment]
I had the same error 
by adding -Xmx200G as a parameter the error was resolved
