### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by kjestradag** [broadinstitute/pilon#128]
I am having troubles trying to run pilon on a 100mb genome with a bam file of 6bg generated from the Bowtie2 tool with illumina mate pair reads. I use the same command with a 6gb bam but from a paired end library and Pilon finished without any problem.

Iam doing:
JAVA_TOOL_OPTIONS="-Xmx400G -Xss2560k"
java -jar pilon-assembly-1.23.jar --threads 1 --genome genome.fasta --frags file.bam --output pilonoutput --outdir pilonoutput --changes

thanks !

Karel

**Comment by zhouhanxiaoxiao** [comment]
Is the problem solved? I had the same problem.

**Comment by avera1988** [comment]
Hi, same issue here, when load pilon from a conda environment:

```
Pilon version 1.24 Thu Jan 28 13:00:45 2021 -0500                                                                                                                                             
Genome: DNAniij33.fitlong.flye.racon.2.fa                                                                                                                                                     
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space                                                                                                                        
        at org.broadinstitute.pilon.GenomeRegion.<init>(GenomeRegion.scala:59)                                                                                                                
        at org.broadinstitute.pilon.GenomeFile.$anonfun$contigRegions$1(GenomeFile.scala:73)                                                                                                  
        at org.broadinstitute.pilon.GenomeFile.$anonfun$contigRegions$1$adapted(GenomeFile.scala:73)                                                                                          
        at org.broadinstitute.pilon.GenomeFile$$Lambda$23/1459672753.apply(Unknown Source)                                                                                                    
        at scala.collection.immutable.Range.map(Range.scala:59)                                                                                                                               
        at org.broadinstitute.pilon.GenomeFile.contigRegions(GenomeFile.scala:73)                                                                                                             
        at org.broadinstitute.pilon.GenomeFile.$anonfun$regions$1(GenomeFile.scala:53)                                                                                                        
        at org.broadinstitute.pilon.GenomeFile$$Lambda$22/1597249648.apply(Unknown Source)                                                                                                    
        at scala.collection.immutable.List.map(List.scala:250)                                                                                                                                
        at org.broadinstitute.pilon.GenomeFile.<init>(GenomeFile.scala:53)                                                                                                                    
        at org.broadinstitute.pilon.Pilon$.main(Pilon.scala:108)                                                                                                                              
        at org.broadinstitute.pilon.Pilon.main(Pilon.scala) 
```
I tried to use directly the .jar file and increase the RAM by: 

```
java -jar /home/avera/mycondaenv/Trycycler/share/pilon-1.24-0/pilon.jar -Xmx120G --threads 16 --genome DNAniij33.fitlong.fl
ye.racon.2.fa --frags illumina_alignments.bam --output DNAniij33.fitlong.flye.racon.2.pilon --changes
Pilon version 1.24 Thu Jan 28 13:00:45 2021 -0500
Unknown option -Xmx120G

```

However, it seems the new version of pilon does not recognize the option -Xmx . Any idea on how to solve this??

Thanks!

Arturo.

**Comment by Valentin-Bio-zz** [comment]
Hello the -Xmx is a java flag not a pilon flag so this is how it works:

In my case I set 900G of maximum mem usage:

`java -Xmx900G -jar pilon-1.24.jar --genome contigs.fasta --bam alignment.sort.bam --output refined --outdir pilon_output/ --changes --vcf --diploid --fix all`
