### ISSUE TITLE
trying to polish nanopore with illumina don't understand the error

### ISSUE THREAD

**Issue by Ayse1006** [broadinstitute/pilon#133]
Hello, I runned the following command : 

`java -Xmx64G -jar pilon-1.24.jar --genome nano.fasta --frags illumina.sorted.bam --changes --fix all `

But the script end before with the following problem : 
``` at scala.Predef$.require(Predef.scala:338)
	at org.broadinstitute.pilon.BamFile.validateSeqs(BamFile.scala:78)
	at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$1(GenomeFile.scala:87)
	at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$1$adapted(GenomeFile.scala:87)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.broadinstitute.pilon.GenomeFile.processRegions(GenomeFile.scala:87)
	at org.broadinstitute.pilon.Pilon$.main(Pilon.scala:111)
	at org.broadinstitute.pilon.Pilon.main(Pilon.scala)
```
I don't really know why... I checked other issues but no answer yet. I also checkes my bam file and it seems correct.
Any help would be appreciated.

**Comment by DylanDSouzaInd** [comment]
> 

Hi Ayse. Did you find a solution to this? I have the faced the same issue and need assistance.

**Comment by JWang52md** [comment]
I have the same issue
