### ISSUE TITLE
"main" java.lang.IllegalArgumentException: requirement failed

### ISSUE THREAD

**Issue by bioramg** [broadinstitute/pilon#144]
Hello,
I am trying to polish the ONT assembly with Illumina reads. When I try to execute, I am getting an error
Command:
 java -Xmx200G -jar /home/bin/pilon-1.23.jar --genome /home/ont/ont.fasta --frags /home/illumina/ont_1_bowtie.bam

Error:
Pilon version 1.23 Mon Nov 26 16:04:05 2018 -0500
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: /home/illumina/ont_1_bowtie.bam must be indexed BAM
        at scala.Predef$.require(Predef.scala:277)
        at org.broadinstitute.pilon.BamFile.<init>(BamFile.scala:58)
        at org.broadinstitute.pilon.Pilon$.optionParse(Pilon.scala:160)
        at org.broadinstitute.pilon.Pilon$.main(Pilon.scala:76)
        at org.broadinstitute.pilon.Pilon.main(Pilon.scala)

Thank you and looking forward to hearing from you.

**Comment by salvatierra8** [comment]
Did you ever find a solution or cause for this issue?

**Comment by mlarjim** [comment]
Hi, your bam file must be indexed (you should have a *.bam.bai in the same folder of your *.bam)
The indexed bam is easily obtained with samtools:
`samtools index <your bam file>`
