### ISSUE TITLE
Index -1 out of bounds for length X

### ISSUE THREAD

**Issue by anitajnorman** [broadinstitute/pilon#150]
Hello,

I've been trying to run Pilon several times with different parameters and it seems to always fail when it tries to process the second batch of scaffold_1:

Finished processing scaffold_1:1-9688624
Processing scaffold_1:9688625-19377248

Can anyone tell me why this might be the case?

Thanks in advance.

Anita

Call:

`java -Xmx700G -jar /proj/nobackup/snic2021-6-72/software/pilon/pilon-1.24.jar \
	--genome $REF \
	--fix all \
	--changes \
	--bam $FRAGS \
	--output $OUTFILE \
        --verbose --vcf --diploid --tracks`

Full error msg:

`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 9688624
	at org.broadinstitute.pilon.PileUpRegion.$anonfun$addRead$5(PileUpRegion.scala:161)
	at org.broadinstitute.pilon.PileUpRegion.$anonfun$addRead$5$adapted(PileUpRegion.scala:145)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at org.broadinstitute.pilon.PileUpRegion.addRead(PileUpRegion.scala:145)
	at org.broadinstitute.pilon.BamFile.$anonfun$process$1(BamFile.scala:133)
	at org.broadinstitute.pilon.BamFile.$anonfun$process$1$adapted(BamFile.scala:126)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
	at org.broadinstitute.pilon.BamFile.process(BamFile.scala:126)
	at org.broadinstitute.pilon.GenomeRegion.processBam(GenomeRegion.scala:294)
	at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$5(GenomeFile.scala:105)
	at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$5$adapted(GenomeFile.scala:105)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$4(GenomeFile.scala:105)
	at org.broadinstitute.pilon.GenomeFile.$anonfun$processRegions$4$adapted(GenomeFile.scala:102)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.broadinstitute.pilon.GenomeFile.processRegions(GenomeFile.scala:102)
	at org.broadinstitute.pilon.Pilon$.main(Pilon.scala:111)
	at org.broadinstitute.pilon.Pilon.main(Pilon.scala)`

**Comment by tamsinlh** [comment]
Anita, 

Did you have any luck resolving this? I am receiving a similar error and am stuck.

**Comment by davidryderuk2** [comment]
I realise I'm a bit late here, but, in my case the issue was solved by indexing the bam file:

samtools index alignment.bam
