### ISSUE TITLE
Asking for indexed bam file

### ISSUE THREAD

**Issue by saras224** [broadinstitute/pilon#158]
Hi @bwlang 
I encountered an error saying that it needs an indexed bam file when I have already provided it an indexed bam file. How to resolved this error? Log of the terminal output:

Pilon version 1.24 Thu Jan 28 13:00:45 2021 -0500
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: /lustre/saraswati/WASTEWATER3/WW_NOVA_SORTED.bam.bai must be indexed BAM
	at scala.Predef$.require(Predef.scala:338)
	at org.broadinstitute.pilon.BamFile.<init>(BamFile.scala:58)
	at org.broadinstitute.pilon.Pilon$.optionParse(Pilon.scala:165)
	at org.broadinstitute.pilon.Pilon$.optionParse(Pilon.scala:172)
	at org.broadinstitute.pilon.Pilon$.main(Pilon.scala:84)
	at org.broadinstitute.pilon.Pilon.main(Pilon.scala)

Thanks in Advance!

**Comment by bwlang** [comment]
i'm not really connected with this project... but that error message reads to me like you might have specified the index (.bai) instead of the bam ??
