### ISSUE TITLE
Unknown Exception

### ISSUE THREAD

**Issue by kevlim83** [broadinstitute/pilon#33]
Hi,

I have tried pilon to polish our pacbio assembly using illumina reads.

The first time I tried it with a canu assembly it worked with no problems.
The second time was with a falcon assembly, it threw some exceptions which I could not figure:
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.ArithmeticException: / by zero
        at org.broadinstitute.pilon.GenomeFile.contigRegions(GenomeFile.scala:71)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$2.apply(GenomeFile.scala:53)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$2.apply(GenomeFile.scala:53)
        at scala.collection.immutable.List.map(List.scala:277)
        at org.broadinstitute.pilon.GenomeFile.<init>(GenomeFile.scala:53)
        at org.broadinstitute.pilon.Pilon$.main(Pilon.scala:98)
        at org.broadinstitute.pilon.Pilon.main(Pilon.scala)
        ... 6 more

Please let me know if you have ideas how to resolve this.

Thanks.

**Comment by w1bw** [comment]
Sorry for the delay in responding, but I'm finally catching up on pilon support. It looks as if this could only happen if there are zero-length contigs in the assembly.  That's bizarre...does Falcon generate such things?
