### ISSUE TITLE
Predef.scala:224

### ISSUE THREAD

**Issue by diaparim** [broadinstitute/pilon#45]
Hi, 

I used pilon with the following command:
java -Xmx256g -jar ~/bin/software/pilon/pilon-1.22.jar --genome ./Phco/output/contigs.fa --jumps sorted.bam --output pilon1 --fix all --mindepth 0.5 --changes --verbose --vcf
It worked well before.

Then I run for the second, but i only saw this messages, and the run stop. any help?

0003815, tig00002995, tig00004231, tig00014389, tig00001872, tig00003722, tig00002515, tig00001202, tig00005432, tig00002706, tig00009748, tig00001066, tig00013488, tig00006621, tig00010413, tig00003413, tig00001249, tig00011538, tig00004747, tig00002265, tig00003244, tig00010517, tig00004960, tig00005041, tig00001175, tig00005472, tig00010377, tig00004546, tig00003204
        at scala.Predef$.require(Predef.scala:224)
        at org.broadinstitute.pilon.BamFile.validateSeqs(BamFile.scala:67)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$processRegions$2.apply(GenomeFile.scala:87)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$processRegions$2.apply(GenomeFile.scala:87)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.broadinstitute.pilon.GenomeFile.processRegions(GenomeFile.scala:87)
        at org.broadinstitute.pilon.Pilon$.main(Pilon.scala:101)
        at org.broadinstitute.pilon.Pilon.main(Pilon.scala)
        ... 6 more

Thanks, 
Marwan

**Comment by diaparim** [comment]
turned out the genome was not the correct one.

Thanks
