### ISSUE TITLE
use pilon to polish cause error

### ISSUE THREAD

**Issue by lijingjing1** [broadinstitute/pilon#57]
Writing Contig1491|arrow:8180512-16361022 VCF to Sample.101.id/Sample.101.id.vcf
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.IllegalArgumentException: requirement failed: can't fetch base outside region

i have a scaffold can't fetch base outside region?

**Comment by wenjiexiaomeng** [comment]
I also got this problem，have you solved this?
