### ISSUE TITLE
Error in main 

### ISSUE THREAD

**Issue by dUmich** [broadinstitute/pilon#75]
I am not familiar with Java so sorry if this is a basic error. When I run pilon 1.22 on a single BAM file I get the error below. It looks like the program is failing to create a moab.fasta file or is failing before it can create it. 

/opt/moab
Rush_KPC_330_test_pilon
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.io.FileNotFoundException: Rush_KPC_330_test_pilon/opt/moab.fasta (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileWriter.<init>(Unknown Source)
	at org.broadinstitute.pilon.GenomeFile.processRegions(GenomeFile.scala:134)
	at org.broadinstitute.pilon.Pilon$.main(Pilon.scala:101)
	at org.broadinstitute.pilon.Pilon.main(Pilon.scala)
	... 6 more

**Comment by dUmich** [comment]
FIXED:
The variable I used as input to the --output option was a bash internal variable for "/opt/moab"
