### ISSUE TITLE
java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by MichelMoser** [broadinstitute/pilon#84]
Dear Pilon developers, 

When running pilon on some medaka output, i get following error: 

Exception in thread "main" java.lang.ArithmeticException: / by zero
        at org.broadinstitute.pilon.GenomeFile.contigRegions(GenomeFile.scala:71)
        at org.broadinstitute.pilon.GenomeFile.$anonfun$regions$1(GenomeFile.scala:53)
        at scala.collection.immutable.List.map(List.scala:286)
        at org.broadinstitute.pilon.GenomeFile.<init>(GenomeFile.scala:53)
        at org.broadinstitute.pilon.Pilon$.main(Pilon.scala:102)
        at org.broadinstitute.pilon.Pilon.main(Pilon.scala)

I checked for contigs with length 0 but shortest contig in assembly is 4 bases. 
It it creating the error? 

Thanks, Michel

**Comment by MichelMoser** [comment]
Sorry, there was a 0 length contig in there. Just spotted it too late =)
