### ISSUE TITLE
--targets list reading error

### ISSUE THREAD

**Issue by KristinaGagalova** [broadinstitute/pilon#88]
Hi,
I am running Pilon with a set of targets. I am having the following error:
```
Target: Ps-1r180608s00050344:41427-49394
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.util.NoSuchElementException: key not found: ./Q903.all.polished.genesLoweAED.function_domain.coordNams.tsv
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
	at org.broadinstitute.pilon.GenomeFile$$anonfun$12.liftedTree1$1(GenomeFile.scala:225)
	at org.broadinstitute.pilon.GenomeFile$$anonfun$12.apply(GenomeFile.scala:225)
	at org.broadinstitute.pilon.GenomeFile$$anonfun$12.apply(GenomeFile.scala:223)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.broadinstitute.pilon.GenomeFile.parseTargetString(GenomeFile.scala:223)
	at org.broadinstitute.pilon.GenomeFile.parseTargets(GenomeFile.scala:254)
	at org.broadinstitute.pilon.GenomeFile.<init>(GenomeFile.scala:50)
	at org.broadinstitute.pilon.Pilon$.main(Pilon.scala:98)
	at org.broadinstitute.pilon.Pilon.main(Pilon.scala)
	... 6 more
```
My file is formatted in this way:
```
Ps-1r180608s00050344:41427-49394,Ps-1r180608s00911611:1505-4121,Ps-1r180608s00018962:161210-166152,Ps-1r180608s00018962:167000-169653,Ps-1r180608s00018962:14631-19514,Ps-1r180608s00016047:4553-8190,Ps-1r180608s00315771:748-7546,Ps-1r180608s00042471:173570-175803,Ps-1r180608s00000707:388790-395489,Ps-1r180608s00000707:112864-115413,Ps-1r180608s00795190:0-2595,Ps-1r180608s00001389:24642-35458,Ps-1r180608s00066062:5597-9653,Ps-1r180608s00019032:11388-14443,Ps-1r180608s00019032:30256-33541,Ps-1r180608s00114258:25712-33051,Ps-1r180608s00095807:6914-12819,Ps-1r180608s00222839:20625-23338,Ps-1r180608s00051098:18129-21725,Ps-1r180608s00051098:20966-24648,Ps-1r180608s00002592:98411-100971,Ps-1r180608s00002592:83182-86624,Ps-1r180608s00002592:44350-47669,Ps-1r180608s00002592:69338-76483,Ps-1r180608s00065649:51569-54522,Ps-1r180608s00016071:114741-118489,Ps-1r180608s00028052:16064-33304,...
```
Pilon version 1.22 Wed Mar 15 16:38:30 2017 -0400

I am sure the naming of the scaffolds is correct. What can be the error here?
Thank you in advance

**Comment by KristinaGagalova** [comment]
We may have found out what is going on. Is there possible that the "-" in the scaffold name does not allow the correct parsing?

**Comment by KristinaGagalova** [comment]
I found out my error. Some of my target ranges are out of the length of my contigs. 
I have corrected it and now it's running.
Maybe add an error message that states that?
Thanks
