### ISSUE TITLE
Error Pilon - Array

### ISSUE THREAD

**Issue by KristinaGagalova** [broadinstitute/pilon#89]
Hi,
I am running Pilon on a large genome (20G) and I have short reads alignments.
I am correcting only snps and short indels in a list of targets.

After running for quite a long time and having the contigs corrected I have the following error:
```
Corrected 0 snps; corrected 0 small insertions totaling 0 bases, 0 small deletions totaling 0 bases
Finished processing Ps-1r180608s00017228:112301-116371
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.ArrayIndexOutOfBoundsException
``` 
Any hints of what that could be?

**Comment by aaronphillips7493** [comment]
I am also having the same issue. I am hoping that by commenting here I can get the ball rolling on a solution as it seems to have stalled :)
